baseURL = 'https://ideas.pinsern.com/'
languageCode = 'en-us'
title = 'Over Engineered'

theme="PaperMod"

enableRobotsTXT=true

[params.homeInfoParams]
Title = "Hi there! My name is Pin Sern"
Content = """
My girlfriend once told me "Can you go find someone who cares?"

So here I am!
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/fangpinsern"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/pin-sern-fang-689539191/"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/colourincrayons/"

[params.assets]
favicon="/favicon.svg"